### PR TITLE
fix: support heritage of sibling modules

### PR DESCRIPTION
**Pull request by retrohacker**
Before this PR, heritage of siblings was fragile, depending on the alphanumeric
sorting of import names in the generated index.ts file.

For example, lets assume HomeownerPingService extends Service.

index.js in the generated namespace would (in order) import
HomeownerPingService.js and Service.js. HomeownerPingService.js then relies on
Service.js to provide Service but, instead of directly importing Service.js, it
instead imports index.js and tries to access the exported Server object.

This access causes an exception to be thrown because, at this point in
evaluation, Service is not yet instantiated - V8 will not instantiate it until
after HomeownerPingService is done being evaluated.

To address this, this PR removes the cyclic dependency for sibling imports by
directly importing the file. This will ensure V8 instantiates the modules
in the order they are encountered in the codebase.

### CODE REVIEW

**Comment by retrohacker** [comment]
As for how we never encountered this before:

It appears webpack was saving us from this bug by by stubbing out the unused HomeownerPingService.js file during tree shaking. Unfortunately server side JS didn't have that luxury since we don't do tree shaking.

@cortiz-statestitle actually ran into this exact bug back in July when using the generated files with a new UI code base. This PR explains why `sideEffects: false` made the exception go away: it shook HomeownerPingService.js out of the tree!

**Comment by cortiz-statestitle** [comment]
Thanks for the explanation, Alan and I worked on that and I remember Alan added the sideEffect and the bug was fixed.

**Review by cortiz-statestitle — APPROVED** [review]
Looks good to me

**Comment by alansouzati** [comment]
yeah the "fix" Ive added was more like a workaround that fits well for folks using webpack. this is indeed a long term fix.

**Pull request merged**
